{{- range $index, $map := .Values.configs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $map.name }}-configmap-{{ $index }}
data:
  source: "range"
  {{- range $key, $val := $map }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}